# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.classes import Classes  # noqa: F401,E501
from swagger_server import util


class Events(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, event_id: int=None, name: str=None, class_id: List[Classes]=None, create_date: datetime=None, status: str=None, happen_date: datetime=None):  # noqa: E501
        """Events - a model defined in Swagger

        :param event_id: The event_id of this Events.  # noqa: E501
        :type event_id: int
        :param name: The name of this Events.  # noqa: E501
        :type name: str
        :param class_id: The class_id of this Events.  # noqa: E501
        :type class_id: List[Classes]
        :param create_date: The create_date of this Events.  # noqa: E501
        :type create_date: datetime
        :param status: The status of this Events.  # noqa: E501
        :type status: str
        :param happen_date: The happen_date of this Events.  # noqa: E501
        :type happen_date: datetime
        """
        self.swagger_types = {
            'event_id': int,
            'name': str,
            'class_id': List[Classes],
            'create_date': datetime,
            'status': str,
            'happen_date': datetime
        }

        self.attribute_map = {
            'event_id': 'event_id',
            'name': 'name',
            'class_id': 'class_id',
            'create_date': 'create_date',
            'status': 'status',
            'happen_date': 'happen_date'
        }
        self._event_id = event_id
        self._name = name
        self._class_id = class_id
        self._create_date = create_date
        self._status = status
        self._happen_date = happen_date

    @classmethod
    def from_dict(cls, dikt) -> 'Events':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The events of this Events.  # noqa: E501
        :rtype: Events
        """
        return util.deserialize_model(dikt, cls)

    @property
    def event_id(self) -> int:
        """Gets the event_id of this Events.


        :return: The event_id of this Events.
        :rtype: int
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id: int):
        """Sets the event_id of this Events.


        :param event_id: The event_id of this Events.
        :type event_id: int
        """

        self._event_id = event_id

    @property
    def name(self) -> str:
        """Gets the name of this Events.


        :return: The name of this Events.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Events.


        :param name: The name of this Events.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def class_id(self) -> List[Classes]:
        """Gets the class_id of this Events.


        :return: The class_id of this Events.
        :rtype: List[Classes]
        """
        return self._class_id

    @class_id.setter
    def class_id(self, class_id: List[Classes]):
        """Sets the class_id of this Events.


        :param class_id: The class_id of this Events.
        :type class_id: List[Classes]
        """
        if class_id is None:
            raise ValueError("Invalid value for `class_id`, must not be `None`")  # noqa: E501

        self._class_id = class_id

    @property
    def create_date(self) -> datetime:
        """Gets the create_date of this Events.


        :return: The create_date of this Events.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date: datetime):
        """Sets the create_date of this Events.


        :param create_date: The create_date of this Events.
        :type create_date: datetime
        """
        if create_date is None:
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    @property
    def status(self) -> str:
        """Gets the status of this Events.


        :return: The status of this Events.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Events.


        :param status: The status of this Events.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def happen_date(self) -> datetime:
        """Gets the happen_date of this Events.


        :return: The happen_date of this Events.
        :rtype: datetime
        """
        return self._happen_date

    @happen_date.setter
    def happen_date(self, happen_date: datetime):
        """Sets the happen_date of this Events.


        :param happen_date: The happen_date of this Events.
        :type happen_date: datetime
        """
        if happen_date is None:
            raise ValueError("Invalid value for `happen_date`, must not be `None`")  # noqa: E501

        self._happen_date = happen_date
