# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.courses import Courses  # noqa: F401,E501
from swagger_server import util


class Exams(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, course_id: Courses=None):  # noqa: E501
        """Exams - a model defined in Swagger

        :param id: The id of this Exams.  # noqa: E501
        :type id: int
        :param name: The name of this Exams.  # noqa: E501
        :type name: str
        :param course_id: The course_id of this Exams.  # noqa: E501
        :type course_id: Courses
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'course_id': Courses
        }

        self.attribute_map = {
            'id': 'Id',
            'name': 'Name',
            'course_id': 'CourseId'
        }
        self._id = id
        self._name = name
        self._course_id = course_id

    @classmethod
    def from_dict(cls, dikt) -> 'Exams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Exams of this Exams.  # noqa: E501
        :rtype: Exams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Exams.


        :return: The id of this Exams.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Exams.


        :param id: The id of this Exams.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Exams.


        :return: The name of this Exams.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Exams.


        :param name: The name of this Exams.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def course_id(self) -> Courses:
        """Gets the course_id of this Exams.


        :return: The course_id of this Exams.
        :rtype: Courses
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: Courses):
        """Sets the course_id of this Exams.


        :param course_id: The course_id of this Exams.
        :type course_id: Courses
        """
        if course_id is None:
            raise ValueError("Invalid value for `course_id`, must not be `None`")  # noqa: E501

        self._course_id = course_id
