# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Courses(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, type: str=None, create_date: datetime=None):  # noqa: E501
        """Courses - a model defined in Swagger

        :param id: The id of this Courses.  # noqa: E501
        :type id: int
        :param name: The name of this Courses.  # noqa: E501
        :type name: str
        :param type: The type of this Courses.  # noqa: E501
        :type type: str
        :param create_date: The create_date of this Courses.  # noqa: E501
        :type create_date: datetime
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'type': str,
            'create_date': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type',
            'create_date': 'create_date'
        }
        self._id = id
        self._name = name
        self._type = type
        self._create_date = create_date

    @classmethod
    def from_dict(cls, dikt) -> 'Courses':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The courses of this Courses.  # noqa: E501
        :rtype: Courses
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Courses.


        :return: The id of this Courses.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Courses.


        :param id: The id of this Courses.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Courses.


        :return: The name of this Courses.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Courses.


        :param name: The name of this Courses.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> str:
        """Gets the type of this Courses.


        :return: The type of this Courses.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Courses.


        :param type: The type of this Courses.
        :type type: str
        """

        self._type = type

    @property
    def create_date(self) -> datetime:
        """Gets the create_date of this Courses.


        :return: The create_date of this Courses.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date: datetime):
        """Sets the create_date of this Courses.


        :param create_date: The create_date of this Courses.
        :type create_date: datetime
        """

        self._create_date = create_date
