# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.classes import Classes  # noqa: F401,E501
from swagger_server import util


class Events(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, class_id: Classes=None, create_date: datetime=None, status: str=None, happen_date: datetime=None):  # noqa: E501
        """Events - a model defined in Swagger

        :param id: The id of this Events.  # noqa: E501
        :type id: int
        :param name: The name of this Events.  # noqa: E501
        :type name: str
        :param class_id: The class_id of this Events.  # noqa: E501
        :type class_id: Classes
        :param create_date: The create_date of this Events.  # noqa: E501
        :type create_date: datetime
        :param status: The status of this Events.  # noqa: E501
        :type status: str
        :param happen_date: The happen_date of this Events.  # noqa: E501
        :type happen_date: datetime
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'class_id': Classes,
            'create_date': datetime,
            'status': str,
            'happen_date': datetime
        }

        self.attribute_map = {
            'id': 'Id',
            'name': 'Name',
            'class_id': 'ClassId',
            'create_date': 'CreateDate',
            'status': 'Status',
            'happen_date': 'HappenDate'
        }
        self._id = id
        self._name = name
        self._class_id = class_id
        self._create_date = create_date
        self._status = status
        self._happen_date = happen_date

    @classmethod
    def from_dict(cls, dikt) -> 'Events':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Events of this Events.  # noqa: E501
        :rtype: Events
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Events.


        :return: The id of this Events.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Events.


        :param id: The id of this Events.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Events.


        :return: The name of this Events.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Events.


        :param name: The name of this Events.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def class_id(self) -> Classes:
        """Gets the class_id of this Events.


        :return: The class_id of this Events.
        :rtype: Classes
        """
        return self._class_id

    @class_id.setter
    def class_id(self, class_id: Classes):
        """Sets the class_id of this Events.


        :param class_id: The class_id of this Events.
        :type class_id: Classes
        """
        if class_id is None:
            raise ValueError("Invalid value for `class_id`, must not be `None`")  # noqa: E501

        self._class_id = class_id

    @property
    def create_date(self) -> datetime:
        """Gets the create_date of this Events.


        :return: The create_date of this Events.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date: datetime):
        """Sets the create_date of this Events.


        :param create_date: The create_date of this Events.
        :type create_date: datetime
        """
        if create_date is None:
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    @property
    def status(self) -> str:
        """Gets the status of this Events.


        :return: The status of this Events.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Events.


        :param status: The status of this Events.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def happen_date(self) -> datetime:
        """Gets the happen_date of this Events.


        :return: The happen_date of this Events.
        :rtype: datetime
        """
        return self._happen_date

    @happen_date.setter
    def happen_date(self, happen_date: datetime):
        """Sets the happen_date of this Events.


        :param happen_date: The happen_date of this Events.
        :type happen_date: datetime
        """

        self._happen_date = happen_date
