# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.classes import Classes  # noqa: F401,E501
from swagger_server.models.students import Students  # noqa: F401,E501
from swagger_server import util


class Registrations(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, student_id: Students=None, class_id: Classes=None, register_day: datetime=None, status: str=None, create_date: datetime=None):  # noqa: E501
        """Registrations - a model defined in Swagger

        :param student_id: The student_id of this Registrations.  # noqa: E501
        :type student_id: Students
        :param class_id: The class_id of this Registrations.  # noqa: E501
        :type class_id: Classes
        :param register_day: The register_day of this Registrations.  # noqa: E501
        :type register_day: datetime
        :param status: The status of this Registrations.  # noqa: E501
        :type status: str
        :param create_date: The create_date of this Registrations.  # noqa: E501
        :type create_date: datetime
        """
        self.swagger_types = {
            'student_id': Students,
            'class_id': Classes,
            'register_day': datetime,
            'status': str,
            'create_date': datetime
        }

        self.attribute_map = {
            'student_id': 'student_id',
            'class_id': 'class_id',
            'register_day': 'register_day',
            'status': 'status',
            'create_date': 'create_date'
        }
        self._student_id = student_id
        self._class_id = class_id
        self._register_day = register_day
        self._status = status
        self._create_date = create_date

    @classmethod
    def from_dict(cls, dikt) -> 'Registrations':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The registrations of this Registrations.  # noqa: E501
        :rtype: Registrations
        """
        return util.deserialize_model(dikt, cls)

    @property
    def student_id(self) -> Students:
        """Gets the student_id of this Registrations.


        :return: The student_id of this Registrations.
        :rtype: Students
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: Students):
        """Sets the student_id of this Registrations.


        :param student_id: The student_id of this Registrations.
        :type student_id: Students
        """
        if student_id is None:
            raise ValueError("Invalid value for `student_id`, must not be `None`")  # noqa: E501

        self._student_id = student_id

    @property
    def class_id(self) -> Classes:
        """Gets the class_id of this Registrations.


        :return: The class_id of this Registrations.
        :rtype: Classes
        """
        return self._class_id

    @class_id.setter
    def class_id(self, class_id: Classes):
        """Sets the class_id of this Registrations.


        :param class_id: The class_id of this Registrations.
        :type class_id: Classes
        """
        if class_id is None:
            raise ValueError("Invalid value for `class_id`, must not be `None`")  # noqa: E501

        self._class_id = class_id

    @property
    def register_day(self) -> datetime:
        """Gets the register_day of this Registrations.


        :return: The register_day of this Registrations.
        :rtype: datetime
        """
        return self._register_day

    @register_day.setter
    def register_day(self, register_day: datetime):
        """Sets the register_day of this Registrations.


        :param register_day: The register_day of this Registrations.
        :type register_day: datetime
        """
        if register_day is None:
            raise ValueError("Invalid value for `register_day`, must not be `None`")  # noqa: E501

        self._register_day = register_day

    @property
    def status(self) -> str:
        """Gets the status of this Registrations.


        :return: The status of this Registrations.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Registrations.


        :param status: The status of this Registrations.
        :type status: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def create_date(self) -> datetime:
        """Gets the create_date of this Registrations.


        :return: The create_date of this Registrations.
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date: datetime):
        """Sets the create_date of this Registrations.


        :param create_date: The create_date of this Registrations.
        :type create_date: datetime
        """

        self._create_date = create_date
